#!/bin/bash

# Script to launch the multiplayer server.

set -u

# Set the TOMCAT environment variable, assuming that the directory structure
# mirrors that of the git repository.
TOMCAT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../" >/dev/null 2>&1 && pwd)"
export TOMCAT

# TODO: Uncomment the line below once we have multiplayer working properly.
# source "$TOMCAT"/tools/recording_helper

"$TOMCAT"/tools/start_mosquitto
Xvfb :1 -screen 0 1400x900x24 &
export DISPLAY=:1.0
export TOMCAT_FULL_SCREEN=0

"$TOMCAT"/tools/check_minecraft -port 10000
